name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::844479804958:role/todo-app-github-actions
          aws-region: ap-southeast-1

      - name: Install & typecheck backend
        working-directory: backend
        run: |
          npm ci
          npm run typecheck

      - name: Build frontend
        working-directory: frontend
        run: |
          npm ci
          cat > .env <<'EOF'
          VITE_API_URL=https://vriumdbdd3.execute-api.ap-southeast-1.amazonaws.com
          VITE_COGNITO_AUTHORITY=https://cognito-idp.ap-southeast-1.amazonaws.com/ap-southeast-1_yfrGSWLcm
          VITE_COGNITO_CLIENT_ID=2k9797hhlh83f7hb571sp7tf04
          VITE_COGNITO_DOMAIN=https://todo-app-844479804958.auth.ap-southeast-1.amazoncognito.com
          EOF
          npm run build

      - name: Deploy (CDK)
        working-directory: infra
        run: |
          npm ci
          npx cdk deploy TodoAppStack --require-approval never --no-notices
